# Use the external-facing network
infra_external_network_id: "{{ lookup('pipe', 'openstack network show CUDN-Internet -f value -c id') }}"

# Use the pre-existing portal-internal network so that we don't need to steal a router
infra_network_id: "{{ lookup('pipe', 'openstack network show portal-internal -f value -c id') }}"

# The ingress IP comes from an environment variable
infra_fixed_floatingip: "{{ lookup('env', 'INGRESS_IP') }}"

# Flavor auto-detection picks the wrong flavors on Arcus, so override them
#   The flavor to use for the Azimuth AIO VM (vm.azimuth.ci.en1.medium)
infra_flavor_id: 48cccd98-c783-47b9-a429-41dedb38d5f2
#   The flavor to use for the workstation test case (vm.azimuth.ci.ec1.medium)
generate_tests_caas_test_case_workstation_param_cluster_flavor: 2ef4c0c5-0fb3-457d-9573-cb62a43c34f5
#   The flavor to use for the repo2docker test case
generate_tests_caas_test_case_repo2docker_param_cluster_flavor: "{{ generate_tests_caas_test_case_workstation_param_cluster_flavor }}"
#   The flavor to use for the R-Studio test case
generate_tests_caas_test_case_rstudio_param_cluster_flavor: "{{ generate_tests_caas_test_case_workstation_param_cluster_flavor }}"
#   The flavor to use for the nodes in the Slurm test case
#   The flavors to use for the Slurm login and control nodes
generate_tests_caas_test_case_slurm_param_login_flavor: "{{ generate_tests_caas_test_case_workstation_param_cluster_flavor }}"
generate_tests_caas_test_case_slurm_param_control_flavor: "{{ generate_tests_caas_test_case_slurm_param_login_flavor }}"
generate_tests_caas_test_case_slurm_param_compute_flavor: "{{ generate_tests_caas_test_case_slurm_param_login_flavor }}"
#   The flavors to use for the control plane and workers in Kubernetes test cases
generate_tests_kubernetes_test_case_control_plane_size: "{{ generate_tests_caas_test_case_workstation_param_cluster_flavor }}"
generate_tests_kubernetes_test_case_worker_size: "{{ generate_tests_kubernetes_test_case_control_plane_size }}"
#   The flavors to use for the control plane and workers in the Kubernetes apps test cases
generate_tests_kubernetes_apps_k8s_control_plane_size: "{{ generate_tests_kubernetes_test_case_control_plane_size }}"
generate_tests_kubernetes_apps_k8s_worker_size: "{{ generate_tests_kubernetes_test_case_worker_size }}"
