name: Azimuth CI provision
description: Provisions an Azimuth environment using the CI config.
runs:
  using: composite
  steps:
    - name: Deploy Azimuth
      shell: bash
      # Make sure to source the ci environment before running the provision
      run: |
        set -e
        source ./ci.env
        source ./bin/activate "$AZIMUTH_CONFIG_ENVIRONMENT" "$AZIMUTH_ENVIRONMENT"
        ansible-playbook stackhpc.azimuth_ops.provision -e @extra-vars.yml
