---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 7e7e01b3db002a0fea59baa52f61bf66ef207afa
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
