---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 386af1ddadd6b053ca1d51982c0ced799a078903
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
