---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: feat/platform-upgrade-test
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
