---

collections:
  - name: https://github.com/azimuth-cloud/ansible-collection-azimuth-ops.git
    type: git
    version: 0.11.2
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
