---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 6b1dc2d7bc9d02b7b1f9a27491d2df5d7dc0aef1
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
