---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: fix/velero-csi-plugin
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
