---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 97ea6476f3a16e073db1a2129c09980b2a0302ff
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops