---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 5b5a6142669c490918556887e1f17d0c0a43f802
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
