---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: ff7e3d2381f0583c65fc035f7b11e2eb80c11c10
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
