---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: b216e877655165f7644e1eb3523c63913ec886cb
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
