---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 855459670ddc314f554fc442ab8bc7492232c86a
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
