---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 6108c76b073a5b58efaff15337cb76126560574c
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
