---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 0.5.1
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
