---

collections:
  - name: https://github.com/azimuth-cloud/ansible-collection-azimuth-ops.git
    type: git
    version: ci/combined-k8s-tests
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
