---

collections:
  - name: https://github.com/azimuth-cloud/ansible-collection-azimuth-ops.git
    type: git
    version: fix/velero-annotations-initial-deploy
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
