---

collections:
  - name: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: 23f1573dd6d414e05b786329a0aa95528aa9d511
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
