---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.10.4
  featureGates:
    ClusterResourceSet: "true"
    ClusterTopology: "true"
    RuntimeSDK: "true"
    MachineSetPreflightChecks: "true"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: openstack
  namespace: capo-system
spec:
  version: v0.10.5
