---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capo-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.10.4
  manager:
    featureGates:
      ClusterResourceSet: true
      ClusterTopology: true
      RuntimeSDK: true
      MachineSetPreflightChecks: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: openstack
  namespace: capo-system
spec:
  version: v0.10.5
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-bootstrap-system
spec:
  version: v1.10.4
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
spec:
  version: v1.10.4
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-talos-bootstrap-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-talos-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: talos
  namespace: capi-talos-bootstrap-system
spec:
  version: v0.6.12
  fetchConfig:
    url: https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/releases/download/v0.6.12/bootstrap-components.yaml
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: talos
  namespace: capi-talos-control-plane-system
spec:
  version: v0.5.13
  fetchConfig:
    url: https://github.com/siderolabs/cluster-api-control-plane-provider-talos/releases/download/v0.5.13/control-plane-components.yaml
