---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/azimuth-cloud/azimuth-config/stack-hpc/secrets
  ref:
    tag: {{ .Values.artifactTag }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-decryption
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: OCIRepository
    name: secrets
  decryption:
    provider: sops
    secretRef:
      name: {{ .Values.sopsSecretName }}
  path: "."
  prune: true
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: dynamic-azimuth-info
      - kind: ConfigMap
        name: static-azimuth-info
        optional: true
