---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azimuth-cloud-capi-helm-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://azimuth-cloud.github.io/capi-helm-charts
