---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - azimuth-cloud.yaml
  - bitnami-labs.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - prometheus-community.yaml
  - cloud-provider-openstack.yaml
  - azimuth-schedule-operator.yaml
  - metrics-server.yaml
  - azimuth-cloud-capi-helm-charts.yaml
  - grafana.yaml
