apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: monitoring
  namespace: monitoring-system
spec:
  type: "oci"
  interval: 15m
  url: oci://ghcr.io/prometheus-community/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-system
spec:
  interval: 30s
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=87.0.0"
      sourceRef:
        kind: HelmRepository
        name: monitoring
  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
    remediation:
      retries: 3 # Number of retries before giving up
      remediateLastFailure: true # Automatically remediate the last failure
  upgrade:
    force: true
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
    remediation:
      retries: 3 # Number of retries before giving up
      remediateLastFailure: true # Automatically remediate the last failure
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: prom-stack-values-default
    - kind: ConfigMap
      name: prom-stack-values
      optional: true