apiVersion: v1
kind: ConfigMap
metadata:
  name: coral-credits-values-default
  namespace: coral-credits
data:
  values.yaml: |
    ingress:
      host: "credits.${DOMAIN}"
      className: traefik
      tls:
        enabled: ${TLS_ENABLED}
        secretName: "coral-credits-tls"
        annotations:
          cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER:-none}
    settings:
      superuserUsername: admin
      database:
        engine: "django.db.backends.postgresql"
        name: coral-credits-db
        host: "coral-credits-db-primary.coral-credits.svc.cluster.local"
        port: "5432"
