# Info: `cacert` attribute can be added to `stringData` to provide Openstack’s CA certificate if needed.
---
apiVersion: v1
kind: Secret
metadata:
  name: azimuth-cluster-cloud-config
  namespace: azimuth-cluster
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: ${openstack_auth_url}
          application_credential_id: ${openstack_application_credential_id}
          application_credential_secret: ${openstack_application_credential_secret}
          project_name: ${openstack_tenant_name}
        region_name: ${openstack_region_name}
        interface: public
        identity_api_version: 3
        auth_type: v3applicationcredential