---

# Use the first available external network
infra_external_network_id: >-
  {{
    lookup('pipe', 'openstack network list --external -f json') |
      from_json |
      first |
      default(undef(hint = 'Unable to find external network')) |
      json_query('ID')
  }}

# For the infra, we need at least 8GB RAM, but 16GB is better, plus at least 4 CPUs
infra_flavor_id: dcad12ab-aed9-4adc-93a7-e135bf19053d

#infra_image_id: 48c078a5-fd89-4f61-9d6a-c4f48745c0ae

# Upload images as private
# CaaS/Kubernetes will only work within the tenancy in which Azimuth is deployed
community_images_default_visibility: private
# However don't assume we are in control of the images, e.g. if there is another
# Azimuth deployment on the same cloud
community_images_update_existing_visibility: false

# Disable HTTPS and certificate verification everywhere to avoid certificate issues
ingress_tls_enabled: false

# Disable SSL verification for OpenStack in case it uses a custom CA
azimuth_openstack_verify_ssl: false

azimuth_current_cloud_name: demo

# Use secrets that are not really secret for ease
harbor_admin_password: admin
harbor_secret_key: abcdefghijklmnop
awx_admin_password: admin
zenith_registrar_subdomain_token_signing_key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789AA
azimuth_secret_key: 9876543210ZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjihgfedcda00
