---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: monitoring-system
  namespace: monitoring-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/azimuth-cloud/azimuth-config/stack-hpc/monitoring-system
  ref:
    tag: ${FLUX_ARTIFACT_TAG}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring-system
  sourceRef:
    kind: OCIRepository
    name: monitoring-system
    namespace: monitoring-system
  path: "./kube-prometheus-stack"
  prune: true
  wait: true
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: dynamic-azimuth-info
      - kind: ConfigMap
        name: static-azimuth-info
        optional: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: monitoring-system
  sourceRef:
    kind: OCIRepository
    name: monitoring-system
    namespace: monitoring-system
  dependsOn:
    - name: kube-prometheus-stack
  path: "./monitoring"
  prune: true
  wait: true
  timeout: 3m
  retryInterval: 1m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: dynamic-azimuth-info
      - kind: ConfigMap
        name: static-azimuth-info
        optional: true
