---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m0s
  url: oci://ghcr.io/azimuth-cloud/azimuth-config/stack-hpc/traefik
  ref:
    tag: ${FLUX_ARTIFACT_TAG}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: traefik
  sourceRef:
    kind: OCIRepository
    name: traefik
    namespace: traefik
  path: "."
  prune: true
  timeout: 3m
  dependsOn:
    - name: kube-prometheus-stack
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: dynamic-azimuth-info
      - kind: ConfigMap
        name: static-azimuth-info
        optional: true
