---

kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

# assumes the host VM is also hosting the cluster, this may need to be overridden 
infra_external_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
ingress_base_domain: "apps.{{ infra_external_ip | replace('.', '-') }}.sslip.io"


#infra_external_network_id: "{{ infra_external_ip }}"
# Use the same external network as we use for the infra
#azimuth_capi_operator_external_network_id: "{{ infra_external_network_id }}"

# Disable HTTPS and certificate verification everywhere to avoid certificate issues
ingress_tls_enabled: false #this will probably break things 

azimuth_current_cloud_name: k3s-azimuth 

# Disabling things that will not work without openstack
azimuth_clusters_enabled: no 

azimuth_kubernetes_enabled: no

azimuth_capi_operator_release_overrides:
  config:
    identity:
      oidcEnabled: true
flux_enabled: true
azimuth_authentication_type: oidc
##ingress_tls_enabled: true

azimuth_chart_version: 0.15.0

cloud_metrics_enabled: false #saves a lot of storage, not currently in use + grafana seems to have issues 

certmanager_monitoring_enabled: false # certmanager tries to setup monitoring (UNTESTED)

azimuth_cloud_provider_type: "null" # stops it expecting openstack 
# yes it has to be "null", and not null. 
