apiVersion: v1
kind: Secret
metadata:
    name: azimuth-secret-key
    namespace: azimuth
data:
    secretKey: ENC[AES256_GCM,data:5l55cWl0a5s4MPMNG/jwO5GSwsQDcy5qdmReb4s9T26GtUwzeaXrTxAFwZIYYzn4ZZCS/8rFh9P6T/M=,iv:CrzUzgqBeGKifZeSsWTbTHGlb1Sq7sRS0vUcrMZos4s=,tag:PT8sS7owVxkgBb/5ALwKsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ciswK083Z1RjS0xvTG1V
            bzBpNGFuV1V2K0FqWEF1WGgvbGoxOHJBVlRvCnJjaUJzTmo1SzM0TzZwQ1IrT0My
            YWZIcllpYVljS2VrZFRFZi9jWkVqUDgKLS0tIEY3NnlrUUxDcUZYUFBMdGgzd3FE
            ekRDRkRXbjZqeFFSV2FMaGRqRk90LzQKW+Py6e5yWW1tlrskFWi9oO2QwQW8F3XK
            EoKWgDdEgUnsZhnuO6K2IyXCEuhEcgDh8ntiBzL6O69XWFJ29HYsLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T15:10:25Z"
    mac: ENC[AES256_GCM,data:PtExKrFw8keiz3s49GFnSffaYeOo7gZxva2CXrd6bPlXrCeXZ/P9hvrM/WgA5aVrXHFjadREdbgi458lk2wUIL09F7OS5zr8vC1nEYIXy9+zWq+7FIdlwwviWU2xKpJyhvYcajscuKRtqFxAGXyXbWHqA1t7Sb+MGLij+acr1jQ=,iv:QiAb1WqIPxx90CvDjCvIt2+rLWLwvM8+HDavAIdOloA=,tag:r/eTT/KFb3xbOVUv35XdMw==,type:str]
    version: 3.13.3
