apiVersion: v1
kind: Secret
metadata:
    name: azimuth-secret-key
    namespace: azimuth
data:
    secretKey: ENC[AES256_GCM,data:hvu0GedEIfTgZVPDcqTZIMXbtOdL5+2OmJLXIgsvFr7D95Zfpe/CQXdkjkxx3fFiWWU6hCp4oIG1VaaXaMx+iWBLjVTvobZpvj+OH2JnYdw=,iv:uZWTA3BDm1HY/QfLhXIGQN376C10wvf0yip+XTox6XE=,tag:tIu1Lv83gEivweVy10JqiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb2RzZ0REbnJIUHBVMUVh
            bnRVQWpiUHpOcnVmQW4vRnhIR0p0YlllSkVrCmhaYWVWdUM3Mk5NK0hNRzljbzRG
            K1RLLzEyNnNockV1SGF6a01KK3dTQ1EKLS0tIGhGMHJDcHVpei85a2tOQ2o1aGpI
            ZXN6ZTAyWERzZzhPQXpzaWQ3dWg4MkUKlE/S5MGDCAK5Zr1qlOW2aOydJyNHBCcA
            qQKbZK+7RXJ+iVKRpTTAYy31l7/pWiDU2lDdkZBaowhsGd9JbUhJ9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T15:28:51Z"
    mac: ENC[AES256_GCM,data:NU+NGYlhYmk5YsZT/EjvyTGsYrfWRXWgMl1+Zdku9NwZ2XQSCKg/mE65JOWE4MayePOUUITcGbREn5pphne7A27K9QUxG7ruOb0jAvUu9KUQPZvA22/bN2Cp9rgE1vrGXquTXgu3JmyjdDEORL79bSXXFl1AlnoK5tjvxnSLI+0=,iv:w8ihUuQQS0htTV/5ja6gUzNYkNiPUToHaahhI2IAYfU=,tag:Zc6T3jICS3G52zxKBN/c3w==,type:str]
    version: 3.13.3
