apiVersion: v1
kind: Secret
metadata:
    name: coral-credits-admin
    namespace: coral-credits
data:
    password: ENC[AES256_GCM,data:KpyHZ3NYqxKZXRPJT+JpFtZdz9R9UT6Z8XWuwyUfMi8XY01i,iv:Fnm9TWTOIFWovS0Kd5baF6l62WWVpDW/e/DWAQJzMTM=,tag:GiBw96cx0EZDa/R+oZLXlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd1NFUXRRU2VVT1VnQzN0
            aXZVaXlGZS9KQTRFWDhUTXdacnBwdTJsWFJVCmJzV2M2YkRaQWozYWhlREErZWlu
            Sk9PQ05uMDdUTHBzQWwydnQ4aDF3bmcKLS0tIHpIemdVQllBdVJGSVlRYVUxWEFG
            V2x6NmdET3lhVEgzNWh5a1I4Ulp0ZW8KPuLHT73u8k5vRvuCGV7VpV/M6NKl80o6
            6/Ut3XxWI7qYZJldm3AzLnWRpFzOthHlwmfhQZfrMHI47DNr58dEcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T14:31:03Z"
    mac: ENC[AES256_GCM,data:3i5pKbN48/YQDnLA3Xz8vF4tzWAZHMO/U41jOplrbvSzbIcKB/Zg357Ce8fBKS86anQu2Tc0LduUiNPtwMM+w6sn5AVb1B/BITzwGVYFP+qSIw8lfBHUzlHBCXA+VCMrNwgMBxTVsybOiz0nNgkUr2ZzJXV1OXfLsEY8Isz29mM=,iv:xln7dc3IGa3kxU/RIXiRpUwgaLcYjlhAgX9b+kKiNN4=,tag:qlo9FvnJLrTE36eOzGxmvA==,type:str]
    version: 3.13.3
