apiVersion: v1
kind: Secret
metadata:
    name: harbor-secret-key
    namespace: harbor
data:
    secretKey: ENC[AES256_GCM,data:6stTdwCsjfPGNJxCGDWCsW+MbhPMhYDZ,iv:iqVjKX/4P8PCZbC9rxDkYyaOkqo5lhCYvPGtfgcFpJA=,tag:eqdMHta3Xtm/30F5UjUnjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cFZES1RkWmlZVzg0ZVRC
            ZEJtaVZZMlZVeFJPclVmKzFCQkgrek5TcVNzCjVFQ1czTnlLcEJPUXo5OFRnRFZU
            b2w1MjYyVVpQbllFTTJoOFg0RHhkU2MKLS0tIGNENmlEdjRteVBiS2grM3Rid2tB
            L3k2bUcxSFVDKzgyOXpYbFBMeVhDU1EKYV3HpSqpV6oWwl4reqv3FeFcnB4KbBbe
            CvvoSlTox+CdmLuNwFCli7Qfo+OAiyXWn8LERc8Vk7xs4yviQIEhJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T14:18:57Z"
    mac: ENC[AES256_GCM,data:7tDUusFYeSB05K2KKlhMH4sKlT2HCvWvIuR1NgcRGrDdUILYH4gEyy1ejsE6Eh/VmPlzeNsXbhT7fOzSKN82ZOi7X+Htr1Uol3Cpmxxgzvk4UWulFUYWSGrFAF+DTiPHvbejHDVYsp255rswxn9aRxuzksZdTVJlZc7LpR5xKhU=,iv:NwLjT4U20rv/oScQ4REykivgtY0h7PyI+CzP4g9sRw4=,tag:ejRl+NWABdGtT0hlSxHccQ==,type:str]
    version: 3.13.3
