apiVersion: v1
kind: Secret
metadata:
    name: harbor-admin-password
    namespace: harbor
data:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:UBqh6q1T9TsqM8ESlkN2sbVhr67MNF1lYINUnLd62+XuvYWPPZ4AHGOWGws=,iv:IWnMArSO10H7l/gBjSDOl2GCGztBSSncdMpqfxKIvJg=,tag:pqk3R+2USQb+LWGZqk8Xow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd3hqQmZUWHRSM0FiSlpk
            MjVHV3JFNmlFUmtMa1lzWlR4TDNidlAvbkRVCmUvT3RvOEV5RXRubzl4S3N1Rk55
            RitDZ2lCWmJycFExNWU1NTJnMjdRWWMKLS0tIFZjRW1tWDRZbUJlNkYxdWRreHBM
            ZVlRT3gzZHMyU3NxRnBvQ1FtUFV1MnMKKEkCHrmJwwvV3R5nXqTXVjr4wKeUTErX
            Zi93DIEKtAnPrwPBzo4sfEr1OQUQian/zH4dQLgCP0+/zcueptD2SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T12:54:53Z"
    mac: ENC[AES256_GCM,data:XSl3FbBb0waWnh2ii5xt+N7TZp83gb1oJsalvn+cOrBd3ycOCcOovOlupt9kiahOlhA9Wfx6sy8g09mlku4YOq6Gyrn3z4S90Zag8gmY9EObouYV9FXYs86jdg9rN76ZRTATH0dazAZHTA8Zr5n6j2r7OpPMH0VmBu/xrFevHGY=,iv:oiQL3XQcuzZKay8apq3NoPr6QuMftq9uPnnMx/PfhPY=,tag:TfUULcgFs/grYVdZL7N9kQ==,type:str]
    version: 3.13.3
