apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
type: kubernetes.io/basic-auth
data:
    password: ENC[AES256_GCM,data:LBlCZ3YCyVwQC93KRf650/WLheDXvn4b70HoKAGtS1aHOUMTAWG6C+FYgn8=,iv:gyFDeMZvewX3wluOIIbgcPHAT/xS+g10roV2hXllXBo=,tag:K1O2lUfeIj0dFeFjz44+Sw==,type:str]
    username: ENC[AES256_GCM,data:A+ZIhWFh0nE=,iv:Ka9pWfge+WsaEpjejvZNLWzUC3arRPCWiLtdL/5K2Pc=,tag:Cy7Y4bE/HZOX5i8EBkQbbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRDQxM1lUaG8xazBKZTBx
            ejNqVlp3cWtIKzZ2Ry9vb25aNHF2WjN2YkFjCjdXcUxFUWx1TUw5NGxpSS9Gc1I3
            RnpUcXRQRGlTUThSOWZxM3c1bm9icGcKLS0tIGtMS3NKZWZtRzV5SllQRE42YlFC
            L0YyRHNmbHhPZnU5Yy9qN1JwWmZTaHcK5ukS0crAimTq9SyiyVEjU3zDH/kFy4Z5
            x1zOpe7Jn0hVl6y1Qq8ojfgc0ugAiz2YiRQyXkjHJcUVNHcprnhcdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T13:17:47Z"
    mac: ENC[AES256_GCM,data:n/sTpVCO9RBXUxOJ102XY9FyvahvJkuYiigCWKupEScgVMQIPagNWt3JHCgBrffnCy5tNROAlt8+GosS/BSmZujHhqk/wPocjRspU8ErYEJT2Rx9W0FWiep8v3UZZBrz++Rwugt2kzGlL38is8GFXh/AzpM50u55NUCnoVVDSJo=,iv:PoCerw1Or5bNgP9C5tf30JzK/HyLbOFyM1hcP8pPV6M=,tag:8CoDQw4Qi0xItolsHE9xXA==,type:str]
    version: 3.13.3
