apiVersion: v1
kind: Secret
metadata:
    name: zenith-signing-key
    namespace: azimuth
data:
    subdomainTokenSigningKey: ENC[AES256_GCM,data:5Pc/2JcvjfEa/954GJU/YwbJgKn19s7q2xXBlR0pLkEnGyDk9fBIcKNASjSTnTh9UorIwWsF9jBrzYTWbMdLFA==,iv:NpFHyI0O1cJqKM+HYGe88CbI3LhD2/Xb1LF5JDGQyUU=,tag:s00ZieCZtNgwAY3eMzAIIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWXUyZWtxQjZ6UGdXcFZO
            TTF3Lys5NTdzeVVoSFRKMW5NZTFYRHQvcENrCmFsanhqKy9MM1F3VHBoUzF3M0dG
            b0xnOVB3Snc3K2ZhR0lRRkNlalQ1RmcKLS0tIEVRcXFiT0paVjRETzhJMHljV0ts
            ODRjaHJpMFRwSG9vaWxKeTR4OEs2aTAKuM9qfgvBv/5S3NEJ7Czvn2vy/2HJwGVX
            PYmoAfBcrw+EcYMbtkTPMYLAROKDtWzT8MxCL0fcSj17v+j94FHQfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17te6p3udsxg7fa973u9v23lj5xg3w7x233p6azpx763xx8km4qqsk5phuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T14:02:02Z"
    mac: ENC[AES256_GCM,data:wkbAx/Jaju2YqU16riBTEUjAfQl6Sl8e1t0pjv/MuNYE+1YUZPw7RiRszkv3JpOlr3gj4A5+8kSvuR7l6YzKItuUdwyM2w82qC8NdBeCb225Sp/VsR49fkPV/fVCNPbtLKSZ7TKYHQbUDOnU3yfRjuJ9NxkARUfuTwu/iIE//FQ=,iv:NwtGJPVUElVCQb/g43nAgxRKa5EKoHNo+ctq8HqcN6c=,tag:ANU9z2Du+NXZnkX4ONDvxg==,type:str]
    version: 3.13.3
