---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azimuth-cloud-zenith
  namespace: flux-system
spec:
  interval: 1h
  url: https://azimuth-cloud.github.io/zenith
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azimuth-cloud-azimuth
  namespace: flux-system
spec:
  interval: 1h
  url: https://azimuth-cloud.github.io/azimuth
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azimuth-cloud-capi-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://azimuth-cloud.github.io/azimuth-capi-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azimuth-cloud-capi-addon-provider
  namespace: flux-system
spec:
  interval: 1h
  url: https://azimuth-cloud.github.io/cluster-api-addon-provider
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azimuth-cloud-capi-janitor
  namespace: flux-system
spec:
  interval: 1h
  url: https://azimuth-cloud.github.io/cluster-api-janitor-openstack
