name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  TestDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy cloud creds to file
        run: 'echo "$CLOUD" > clouds.yml'
        shell: bash
        env:
          CLOUD: ${{ secrets.CLOUD }}
      - name: Set OS env vars
        run: export OS_CLOUD=openstack && OS_CLIENT_CONFIG_FILE=${GITHUB_WORKSPACE}/clouds.yml
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      - name: Ensure venv
        run: ./bin/ensure-venv
        shell: bash
      - name: Setup demo env
        run: source ./bin/activate demo
        shell: bash
      - name: Ansible requirements
        run: ansible-galaxy install -f -r requirements.yml
        shell: bash
      - name: Deploy Azimuth
        run: ansible-playbook stackhpc.azimuth_ops.provision
        shell: bash
      
      # debug
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Destroy Azimuth
        if: ${{ always() }}
        run: ansible-playbook stackhpc.azimuth_ops.destroy