name: CI
on:
  pull_request_target:
    types: [opened,synchronize, edited]
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  deploy_internal:
      uses: ./.github/workflows/deploy_internal.yml
      secrets: inherit
      if: github.repository == 'stackhpc/azimuth-config'

  deploy_external:
      uses: ./.github/workflows/deploy_external.yml
      secrets: inherit
      if: github.repository != 'stackhpc/azimuth-config'