name: Deploy External
on: workflow_call

env:
  OS_CLOUD: openstack
  OS_CLIENT_CONFIG_FILE: ${{ github.workspace }}/clouds.yml
  AZIMUTH_CONFIG_ENVIRONMENT: ci
  AZIMUTH_ENVIRONMENT: ci-${{ github.run_id }}

jobs:
  test_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Copy cloud creds to file
        run: 'echo "$CLOUD" > clouds.yml'
        shell: bash
        env:
          CLOUD: ${{ secrets.CLOUD }}
            
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Deploy Azimuth
        id: deploy
        run: ./bin/ci-exec provision

        # uses: nick-fields/retry@v2
        # with:
        #   timeout_minutes: 45
        #   max_attempts: 3
        #   shell: bash
        #   retry_on: error
        #   command: |
        #     source ./bin/activate demo \
        #     && ansible-galaxy install -fr requirements.yml \
        #     && ansible-playbook stackhpc.azimuth_ops.provision \
        #     -e infra_flavor_id=5f9def81-c93f-4c1f-a521-3b810061ff6c

      - name: Check expected alerts are pending or firing
        run: |
          source ./bin/activate $AZIMUTH_CONFIG_ENVIRONMENT $AZIMUTH_ENVIRONMENT \
          && ./bin/check-alerts

      # For debugging failed deployment
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   if: ${{ failure() && steps.deploy.conclusion == 'failure' }}
        # with:
          # limit debug access to certain Github ssh keys
          # limit-access-to-users: sd109 # Doesn't seem to work, still accessible with any ssh key

      - name: Destroy Azimuth
        if: ${{ always() }}
        run: ./bin/ci-exec destroy