name: Demo env deployment test
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened,synchronize,edited]
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  # Required manual approval for PRs from external forks before provisioning any cloud infra
  approve:
    runs-on: ubuntu-latest
    steps:
    - name: Await manual approval for run
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.
      # TODO: Change to != after testing
      if: github.repository == 'stackhpc/azimuth-config'

  deploy_demo_env:
      uses: ./.github/workflows/demo-deploy.yml
      secrets: inherit
