name: Demo env deployment test
on:
  workflow_dispatch:
  # pull_request_target:
  #   types: [opened,synchronize,edited]
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main
  
jobs:
  # TODO: Test this manual approval process somehow
  # Require manual approval for PRs from external forks before provisioning any cloud infra
  # According to these docs: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
  # first-time external contributors will always require approval for workflows triggered by PRs from repo forks apart from 
  # those triggered by `pull_request_target`. Current settings for this repo should be double checked to ensure this is configured.
  approve:
    runs-on: ubuntu-latest
    steps:
    - name: Await manual approval for run
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.
    if: github.repository != 'stackhpc/azimuth-config'

  deploy_demo_env:
    uses: ./.github/workflows/demo-deploy.yml
    secrets: inherit