name: Publish release

on:
  release:
    types:
      - published

jobs:
  generate_release_notes:
    name: Generate consolidated release notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate and update release notes
        uses: ./.github/actions/release-notes
