---
name: Update release notes

permissions:
  # need to be able to update releases
  contents: write

on:
  release:
    types:
      - published

jobs:
  generate_release_notes:
    name: Generate consolidated release notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Generate and update release notes
        uses: ./.github/actions/release-notes
