---
name: Update release notes

permissions:
  # need to be able to update releases
  contents: write

on: # yamllint disable-line rule:truthy
  release:
    types:
      - published

jobs:
  generate_release_notes:
    name: Generate consolidated release notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Generate and update release notes
        uses: ./.github/actions/release-notes
