---
name: Publish artifacts

on: # yamllint disable-line rule:truthy
  # Publish artifacts on every push
  push:
  # Also allow publication to be done via a workflow call
  # In this case, the chart version is returned as an output
  workflow_call:
    inputs:
      ref:
        type: string
        description: The ref to build.
        required: true

jobs:
  push_flux_artifacts:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - alerts
          - composed
          - compose-overrides
          - azimuth-flux
          - kube-prometheus-stack
          - secrets
      fail-fast: false
    permissions:
      contents: read
      id-token: write # needed for signing the images with GitHub OIDC Token
      packages: write # required for pushing container images
      security-events: write # required for pushing SARIF files
    steps:
      # - name: Generate environment name
      #   id: environment
      #   run: |
      #     echo name="${BASE}""${OVERLAY:+-$OVERLAY}${CUSTOMER:+-$CUSTOMER}" >> "$GITHUB_OUTPUT"
      #   env:
      #     BASE: ${{ matrix.base }}
      #     OVERLAY: ${{ matrix.overlay }}
      #     CUSTOMER: ${{ matrix.customer }}

      - name: Check out the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.ref || github.ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Install Flux CLI
        shell: bash
        run: |
          wget -q https://github.com/fluxcd/flux2/releases/download/v2.9.1/flux_2.9.1_linux_amd64.tar.gz \
            -O tarball.tar.gz
          tar -xzvf tarball.tar.gz
          rm tarball.tar.gz
          mkdir -p /home/runner/.local/bin
          mv flux /home/runner/.local/bin/flux

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/azimuth-cloud/azimuth-config/flux/${{ steps.environment.outputs.name }}
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push artifact
        shell: bash
        run: |
          ./flux-components/tools/push-artifact.sh \
            ./flux-components/"${IMAGE}" \
            ghcr.io/azimuth-cloud/azimuth-config/flux/"${IMAGE}" \
            "${TAG}"
        env:
          IMAGE: ${{ matrix.image }}
          TAG: latest
