name: Test Azimuth deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # This job exists so that PRs from outside the main repo are rejected
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the azimuth-config repo
        run: exit ${{ github.repository == 'stackhpc/azimuth-config' && '0' || '1' }}

  run_azimuth_tests:
    needs: [fail_on_remote]
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Azimuth environment
        uses: ./.github/actions/setup
        with:
          os-clouds: ${{ secrets.CLOUD }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Provision Azimuth
        uses: ./.github/actions/provision

      - name: Run Azimuth tests
        uses: ./.github/actions/test

      - name: Destroy Azimuth
        uses: ./.github/actions/destroy
        if: ${{ always() }}
