---
# This workflow proposes updates to the dependencies that dependabot cannot
name: Update dependencies

permissions:
  contents: read
  security-events: write

on:
  # Allow manual executions
  workflow_dispatch:
  # Run nightly
  schedule:
    - cron: "0 0 * * *"

jobs:
  propose_github_release_updates:
    runs-on: ubuntu-latest
    if: github.repository == 'azimuth-cloud/azimuth-config'
    strategy:
      matrix:
        include:
          - key: azimuth-ops
            path: ./requirements.yml
            repository: azimuth-cloud/ansible-collection-azimuth-ops
            prereleases: "yes"
            version_jsonpath: collections[0].version

    name: ${{ matrix.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Check for most recent GitHub release
        id: next
        uses: azimuth-cloud/github-actions/github-latest-release@c0e88a34bb32bb8f2b703f7168f91cdb51d9b761
        with:
          repository: ${{ matrix.repository }}
          prereleases: ${{ matrix.prereleases || 'no' }}

      - name: Update dependency key
        uses: azimuth-cloud/github-actions/config-update@c0e88a34bb32bb8f2b703f7168f91cdb51d9b761
        with:
          path: ${{ matrix.path }}
          updates: |
            ${{ matrix.version_jsonpath }}=${{ steps.next.outputs.version }}

      - name: Generate app token for PR
        uses: azimuth-cloud/github-actions/generate-app-token@c0e88a34bb32bb8f2b703f7168f91cdb51d9b761
        id: generate-app-token
        with:
          repository: ${{ github.repository }}
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          app-private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Propose changes via PR if required
        uses: peter-evans/create-pull-request@3499eb61835cc0015c0b786e203d74b1e8f55e43
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          commit-message: >-
            Update ${{ matrix.key }} to ${{ steps.next.outputs.version }}
          branch: update-dependency/${{ matrix.key }}
          delete-branch: true
          title: >-
            Update ${{ matrix.key }} to ${{ steps.next.outputs.version }}
          body: >
            This PR was created automatically to update
            ${{ matrix.key }} to ${{ steps.next.outputs.version }}.
          labels: |
            automation
            dependency-update
